# http://www.appveyor.com/docs/appveyor-yml

environment:
  matrix:
    - nodejs_version: 10

version: "{build}"
build: off
deploy: off
branches:
  only:
    - master
clone_depth: 1
skip_tags: true
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: "npm test"
